version: '2'

services:

  oereb-print:
    networks:
    - print-network
    image: camptocamp/mapfish_print:3.22
    environment:
      LOG_LEVEL: INFO
      CATALINA_OPTS: >-
        -Xmx512M
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro
    ports:
      - 8680:8080

networks:
  print-network:
    external: true
